language: node_js
cache:
  directories:
    - node_modules
notifications:
  email:
    on_failure: change
node_js:
  - 6
before_script:
  - npm prune
after_success:
  - npm run coveralls
  - rm -fr ./build
  - npm run build
  - npm run semantic-release
