language: node_js
node_js:
  - node
  - 7
  - 6
  - 5
notifications:
  email: false
sudo: false
script:
  - npm run lint
  - npm run test
  - npm run build
after_success:
  - rm -fr ./build
  - npm run build
  - semantic-release pre && npm publish && semantic-release post
